import Head from 'next/head'
import Image from 'next/image'
import Base from '../components/Base'
import styles from '../styles/Home.module.scss';
import { Container } from '@mantine/core';
import Link from "next/link";
export default function Home() {
  return (
    <div className={`${styles.container} ${styles.wrapperBox}`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Base />
        <span className={styles.corner_chip}></span>
      <div className={styles.wrapper}>
      </div>
      <div className={styles.frame_wrapper}>
        <p className={styles.tilte_text}>
          Welcome To 
        </p>
      </div>
      
    </div>
  )
}
